# Generated by Django 5.1.7 on 2026-05-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(db_column='CategoriaID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='UsuarioID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=150, unique=True)),
                ('password_hash', models.CharField(db_column='PasswordHash', max_length=255)),
                ('rol', models.CharField(db_column='Rol', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(db_column='DenunciaID', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=200)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('estado', models.CharField(db_column='Estado', default='Pendiente', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('categoria', models.ForeignKey(db_column='CategoriaID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='denuncias.categoria')),
                ('usuario', models.ForeignKey(db_column='UsuarioID', on_delete=django.db.models.deletion.CASCADE, to='denuncias.usuario')),
            ],
            options={
                'db_table': 'Denuncias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClasificacionIA',
            fields=[
                ('id', models.AutoField(db_column='ClasificacionID', primary_key=True, serialize=False)),
                ('categoria_predicha', models.CharField(db_column='CategoriaPredicha', max_length=100)),
                ('confianza', models.FloatField(db_column='Confianza')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
                ('denuncia', models.ForeignKey(db_column='DenunciaID', on_delete=django.db.models.deletion.CASCADE, to='denuncias.denuncia')),
            ],
            options={
                'db_table': 'ClasificacionIA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Geolocalizacion',
            fields=[
                ('id', models.AutoField(db_column='GeoID', primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(db_column='Latitud', decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(db_column='Longitud', decimal_places=6, max_digits=9)),
                ('direccion', models.CharField(db_column='Direccion', max_length=255)),
                ('denuncia', models.OneToOneField(db_column='DenunciaID', on_delete=django.db.models.deletion.CASCADE, to='denuncias.denuncia')),
            ],
            options={
                'db_table': 'Geolocalizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(db_column='SeguimientoID', primary_key=True, serialize=False)),
                ('comentario', models.CharField(db_column='Comentario', max_length=500)),
                ('estado', models.CharField(db_column='Estado', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
                ('denuncia', models.ForeignKey(db_column='DenunciaID', on_delete=django.db.models.deletion.CASCADE, to='denuncias.denuncia')),
                ('funcionario', models.ForeignKey(db_column='FuncionarioID', on_delete=django.db.models.deletion.CASCADE, to='denuncias.usuario')),
            ],
            options={
                'db_table': 'Seguimiento',
                'managed': True,
            },
        ),
    ]
