# Generated by Django 5.1.7 on 2026-05-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clasificacionia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='denuncia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='geolocalizacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
