# Generated by Django 5.1.7 on 2026-05-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_alter_denuncia_estado_alter_seguimiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacionia',
            name='motivo',
            field=models.CharField(blank=True, db_column='Motivo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionia',
            name='validez',
            field=models.CharField(db_column='Validez', default='Requiere revision', max_length=50),
        ),
    ]
