# Generated by Django 5.1.7 on 2026-05-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='clasificacionia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='denuncia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='geolocalizacion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
