# Generated by Django 5.1.7 on 2026-05-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_clasificacionia_motivo_clasificacionia_validez'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='imagen',
            field=models.ImageField(blank=True, db_column='Imagen', null=True, upload_to='denuncias/'),
        ),
    ]
